// Code generated by yaml_to_go. DO NOT EDIT.
// source: ssz_minimal_one.yaml
package autogenerated

type SszGenericTest struct {
	Title         string   `json:"title"`
	Summary       string   `json:"summary"`
	ForksTimeline string   `json:"forks_timeline"`
	Forks         []string `json:"forks"`
	Config        string   `json:"config"`
	Runner        string   `json:"runner"`
	Handler       string   `json:"handler"`
	TestCases     []struct {
		Type  string   `json:"type"`
		Valid bool     `json:"valid"`
		Value string   `json:"value"`
		Ssz   []byte   `json:"ssz"`
		Tags  []string `json:"tags"`
	} `json:"test_cases"`
}
