package autogenerated

import (
	"bytes"
	"github.com/prysmaticlabs/go-ssz"
	"io/ioutil"
	"testing"

	"github.com/ghodss/yaml"
)

func TestYaml(t *testing.T) {
	file, err := ioutil.ReadFile("ssz_minimal_one_formatted.yaml")
	if err != nil {
		t.Fatalf("Could not load file %v", err)
	}

	s := &SszMinimalTest{}
	if err := yaml.Unmarshal(file, s); err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}
    for _, testCase := range s.TestCases {
    	if &testCase.Attestation != nil {
            encoded, err := ssz.Marshal(testCase.Attestation.Value)
            if err != nil {
            	t.Fatal(err)
			}
            if !bytes.Equal(encoded, testCase.Attestation.Serialized) {
            	t.Fatalf("Wanted %#x, received %#x", testCase.Attestation.Serialized, encoded)
			}
		}
	}
}
