package autogenerated

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"testing"

	"github.com/prysmaticlabs/go-ssz"

	"github.com/ghodss/yaml"
)

func TestYaml(t *testing.T) {
	file, err := ioutil.ReadFile("ssz_minimal_one_formatted.yaml")
	if err != nil {
		t.Fatalf("Could not load file %v", err)
	}

	s := &SszMinimalTest{}
	if err := yaml.Unmarshal(file, s); err != nil {
		t.Fatalf("Failed to unmarshal: %v", err)
	}
	for _, testCase := range s.TestCases {
		if &testCase.Attestation != nil {
			fmt.Println(testCase.Attestation.Value)
			encoded, err := ssz.Marshal(testCase.Attestation.Value)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(encoded, testCase.Attestation.Serialized) {
				fmt.Println(testCase.Attestation.Serialized)
				fmt.Println(encoded)
				t.Fatal("No match")
			}
		}
	}
}
